name: willmarket
description: Will Market Android Version 1


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.7.2+3
  splashscreen: ^1.3.5
  fluttertoast: ^8.1.3
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icon.png